package at.ac.fhcampus.enums;

public class country {
    public enum COUNTRY{
        ARGENTINIA, AUSTRALIA, AUSTRIA, BELGIUM, BRAZIL, BULGARIA, CANADA, CHINA, COLOMBIA, CUBA, CZCECH_REPUBLICA, EGYPT,FRANCE, GERMANY, GREECE, HONG_KONG, HUNGARY, INDIA, INDONESIA, IRELAND, ISRAEL, ITALY, JAPAN, LATVIA, LITHUANIA, MALASYA, MEXICO, MAROCCO, NETHERLANDS, NEW_ZEALAND, NIGERIA
    }
}
