package at.ac.fhcampus.enums;

public enum country {
    ARGENTINA, AUSTRALIA, AUSTRIA, BELGIUM, BRAZIL, BULGARIA, CANADA, CHINA, COLOMBIA, CUBA, CZECH_REPUBLIC, EGYPT,FRANCE, GERMANY, GREECE, HONG_KONG, HUNGARY, INDIA, INDONESIA, IRELAND, ISRAEL, ITALY, JAPAN, LATVIA, LITHUANIA, MALAYSIA, MEXICO, MOROCCO, NETHERLANDS, NEW_ZEALAND, NIGERIA, NORWAY, PHILIPPINES, POLAND, PORTUGAL, ROMANIA, RUSSIA, SAUDI_ARABIA, SERBIA, SINGAPORE, SLOVAKIA, SLOVENIA, SOUTH_AFRICA, SOUTH_KOREA, SWEDEN, SWITZERLAND, TAIWAN, THAILAND, TURKEY, UNITED_ARABIAN_EMIRATES, UKRAINE, UNITED_KINGDOM, UNITED_STATES, VENEZUELA;
}
